#ifndef ZELDA_SAVE_EDITOR_H
#define ZELDA_SAVE_EDITOR_H

#include <cstdint>

namespace zelda64::save_editor {

enum ValueId : int32_t {
    Day,
    Time,
    TimeSpeed,
    Tatl,
    IntroComplete,
    OwlSave,
    BomberCode1,
    BomberCode2,
    BomberCode3,
    BomberCode4,
    BomberCode5,
    Wallet,
    Rupees,
    BankRupees,
    Hearts,
    Health,
    DoubleDefense,
    MagicLevel,
    Magic,
    Sword,
    Shield,
    Quiver,
    BombBag,
    StickUpgrade,
    NutUpgrade,
    SpinAttackLevel,
    Arrows,
    Bombs,
    Bombchus,
    DekuSticks,
    DekuNuts,
    PowderKeg,
    Ocarina,
    FireArrows,
    IceArrows,
    LightArrows,
    MagicBeans,
    MagicBeansCount,
    Bottle1,
    Bottle2,
    Bottle3,
    Bottle4,
    Bottle5,
    Bottle6,
    PictographBox,
    LensOfTruth,
    Hookshot,
    GreatFairySword,
    RoomKey,
    LetterMama,
    LetterKafei,
    PendantOfMemories,
    TingleMapClockTown,
    TingleMapWoodfall,
    TingleMapSnowhead,
    TingleMapRomaniRanch,
    TingleMapGreatBay,
    TingleMapStoneTower,
    DekuMask,
    GoronMask,
    ZoraMask,
    FierceDeityMask,
    MaskOfTruth,
    KafeisMask,
    AllNightMask,
    BunnyHood,
    KeatonMask,
    GaroMask,
    RomaniMask,
    CircusLeaderMask,
    PostmanHat,
    CouplesMask,
    GreatFairyMask,
    GibdoMask,
    DonGeroMask,
    KamaroMask,
    CaptainsHat,
    StoneMask,
    BremenMask,
    BlastMask,
    MaskOfScents,
    GiantsMask,
    HeartPieces,
    BombersNotebook,
    OdolwaRemains,
    GohtRemains,
    GyorgRemains,
    TwinmoldRemains,
    SwampSkulltulaTokens,
    OceanSkulltulaTokens,
    Sonata,
    Lullaby,
    BossaNova,
    Elegy,
    Oath,
    SariasSong,
    SongOfTime,
    SongOfHealing,
    EponasSong,
    SongOfSoaring,
    SongOfStorms,
    SunsSong,
    WoodfallMap,
    WoodfallCompass,
    WoodfallBossKey,
    WoodfallSmallKeys,
    WoodfallStrayFairies,
    SnowheadMap,
    SnowheadCompass,
    SnowheadBossKey,
    SnowheadSmallKeys,
    SnowheadStrayFairies,
    GreatBayMap,
    GreatBayCompass,
    GreatBayBossKey,
    GreatBaySmallKeys,
    GreatBayStrayFairies,
    StoneTowerMap,
    StoneTowerCompass,
    StoneTowerBossKey,
    StoneTowerSmallKeys,
    StoneTowerStrayFairies,
    ValueCount,
};

void set_snapshot_value(ValueId id, int32_t value);
int32_t get_snapshot_value(ValueId id);
void set_pending_value(ValueId id, int32_t value);
int32_t get_pending_value(ValueId id);
bool has_snapshot();
bool should_apply_pending();
void clear_pending();
void reset_pending_to_snapshot();

}

#endif
